version: 2

sources:
  - name: raw
    database: analytics # match your DB name
    schema: raw
    tables:
      - name: customers
      - name: products
      - name: orders

models:
  - name: stg_customers
    columns:
      - name: customer_id
        tests: [unique, not_null]
  - name: stg_products
    columns:
      - name: product_id
        tests: [unique, not_null]
  - name: stg_orders
    columns:
      - name: order_id
        tests: [unique, not_null]

  - name: customer_lifetime_value
    description: "Total orders and revenue per customer over time"
    meta:
      owner: "Derek Acevedo"
      team: "Data Engineering"
      sensitivity: "low"
      tags: ["revenue", "customers", "analytics"]
    columns:
      - name: customer_id
        description: "Unique customer identifier"
        tests: [unique, not_null]
      - name: total_orders
        description: "Number of orders placed by the customer"
      - name: total_revenue
        description: "Total revenue generated by the customer"
      - name: first_order_date
        description: "Date of the first recorded order"
      - name: last_order_date
        description: "Date of the most recent order"

  - name: daily_sales_summary
    description: "Aggregated order revenue by date and category"
    meta:
      owner: "Derek Acevedo"
      team: "Analytics"
      sensitivity: "low"
      tags: ["daily", "sales", "summary", "marts"]
    columns:
      - name: order_date
        description: "Date the orders were placed"
        tests: [not_null]
      - name: category
        description: "Product category"
      - name: total_revenue
        description: "Total revenue generated on that date"
        tests: [not_null]
